### ISSUE TITLE
Device not detected

### ISSUE THREAD

**Issue by x360539** [Slimbook-Team/samsung#2]
I have attempted to run the script a couple of times.

The script recognizes my device (Samsung SSD 970 EVO Plus 2TB). I then select this device from this list of options (5). The scanning process occurs. I then receive the message " No supported SSD detected for Firmware Update!!!"

**Comment by slimbook** [comment]
It is recommended that you check the firmware version of your **970 EVO Plus** specifically, with the Ubuntu disks application, or via terminal with:

> 
>    ` sudo fwupdmgr get-devices`
> or
>      `sudo smartctl --xall /dev/nvme0n1 | grep -i firmware` - (Requires installation of the smartmontools package)
> 

So you can make sure if your disk has the latest version.

In case you have the 2B2QEXM7, it is the lastest one.

In case you have the 3B2QEXM7, you will need to update to  4B2QEXM7

Apparently,  **970 EVO Plus that were launched with firmware version 2B2QEXM7, do not require an update**, so none will be available.

The Samsung_SSD_970_EVO_Plus_4B2QEXM7.iso file is valid for those disks that were released with version 3B2QEXM7.

Here you have more information:
https://forum.endeavouros.com/t/samsung-nvme-firmware-update-how/33263/56

All the best!

**Comment by x360539** [comment]
Thank you for the reply. I do have firmware version 2B2QEXM7. Thank you!
